-- Create price list Schema
CREATE SCHEMA IF NOT EXISTS price_list;
-- DROP SCHEMA IF EXISTS price_list CASCADE;
-- CREATE SCHEMA price_list;

-- Create price list tables inside the price_list schema
--- Create Price List Supporting Tables
CREATE TABLE IF NOT EXISTS price_list.price_categories(
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    level TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_price_categories_name_level UNIQUE (name, level)
);


-- CREATE TABLE IF NOT EXISTS price_list.quote_type(
--     quote_type_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     name TEXT UNIQUE NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

CREATE TABLE IF NOT EXISTS price_list.price_source(
    price_source_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS price_list.unit_of_measure(
    unit_of_measure_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    description TEXT UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX on price_list.price_categories (name);
-- CREATE INDEX on price_list.quote_type (name);
CREATE INDEX on price_list.price_source (name);
CREATE INDEX on price_list.unit_of_measure (name);

--- Create Price List Master Table
CREATE TABLE IF NOT EXISTS price_list.price_list(
    price_list_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    category1_id INT 
        REFERENCES price_list.price_categories(category_id) ON UPDATE CASCADE,
    category2_id INT 
        REFERENCES price_list.price_categories(category_id) ON UPDATE CASCADE,
    category3_id 
        INT REFERENCES price_list.price_categories(category_id) ON UPDATE CASCADE,

    description TEXT,

    -- quote_type_id INT 
    --     REFERENCES price_list.quote_type(quote_type_id) ON UPDATE CASCADE,
    price_source_id INT 
        REFERENCES price_list.price_source(price_source_id) ON UPDATE CASCADE,

    quote_date DATE NOT NULL,

    dim_thickness DECIMAL(8,3),
    dim_width DECIMAL(8,3),
    dim_length DECIMAL(8,3),

    unit_of_measure_id INT 
        REFERENCES price_list.unit_of_measure(unit_of_measure_id) ON UPDATE CASCADE,

    price_value DECIMAL(12,2) NOT NULL,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT price_list_natural_key UNIQUE (
    category1_id,
    category2_id,
    category3_id,
    description,
    quote_date,
    price_source_id)
    
);

CREATE INDEX ON price_list.price_list (category1_id);
CREATE INDEX ON price_list.price_list (category2_id);
CREATE INDEX ON price_list.price_list (category3_id);
-- CREATE INDEX ON price_list.price_list (quote_type_id);
CREATE INDEX ON price_list.price_list (price_source_id);
CREATE INDEX ON price_list.price_list (quote_date);

--- Create Price List Import Log Table
CREATE TABLE IF NOT EXISTS price_list.import_log(
    import_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_file_name TEXT NOT NULL,
    import_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    imported_by TEXT,
    records_processed INT,
    records_successful INT,
    records_failed INT,
    notes TEXT
);

--- Create Price List Import Errors Table
CREATE TABLE IF NOT EXISTS price_list.import_errors(
    error_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id BIGINT 
        REFERENCES price_list.import_log(import_id) ON DELETE CASCADE ON UPDATE CASCADE,
    row_number INT,
    error_message TEXT,
    error_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ON price_list.import_errors (import_id);
CREATE INDEX ON price_list.import_errors (row_number);
CREATE INDEX ON price_list.import_errors (error_timestamp);
CREATE INDEX ON price_list.import_errors (error_message);

-- -- Drop the old unique constraint if it exists
-- ALTER TABLE price_list.price_categories
-- DROP CONSTRAINT IF EXISTS uq_price_categories_name_level;

-- -- Add the new compound unique constraint
-- ALTER TABLE price_list.price_categories
-- ADD CONSTRAINT uq_price_categories_name_level UNIQUE (name, level);

-- -- Add a unique constraint to enforce the natural key
-- -- (category1_id, category2_id, category3_id, quote_date, price_source
-- ALTER TABLE price_list.price_list
-- ADD CONSTRAINT price_list_natural_key UNIQUE (
--     category1_id,
--     category2_id,
--     category3_id,
--     quote_date,
--     price_source_id
-- );




